[workspace]
authors = ["Brandon SchÃ¼hlein <brandon@schuehlein.eu>"]
channels = ["https://conda.modular.com/max-nightly/", "conda-forge"]
name = "advent-of-ðŸ”¥"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "==0.25.7"
